image: erlang:21

before_script:
  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - ssh-keyscan gitlab.nomasystems.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

stages:
  - build
  - test

check format:
  stage: build
  tags:
    - docker
  script:
    - rebar3 fmt --check

build:
  stage: build
  tags:
    - docker
  script:
    - make

test:
  stage: test
  tags:
    - docker
  script:
    - make test
  after_script:
    - rebar3 cover -v
  artifacts:
    reports:
      junit: _build/test/logs/**/report.xml
    paths:
      - _build/test/logs/**/report.xml
      - _build/test/cover/index.html

