name: nbully ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  OTP-VERSION: 26.2.1
  REBAR3-VERSION: 3.22.1

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['25.3.2', '26.2.1']
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ env.REBAR3-VERSION }}

      - uses: actions/cache@v3.2.6
        id: rebar3-cache
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ env.REBAR3-VERSION }}-${{ hashFiles('rebar.lock') }}

      - name: Compile
        run: |
          rebar3 clean
          rebar3 compile

      - run: rebar3 check

      - run: rebar3 test

      - name: Create test summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: '_build/test/logs/**/report.xml'
